name: Close Issues on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  close-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Extract Issue Number
      id: extract_issue
      run: |
        issue_numbers=$(echo "${{ github.event.pull_request.body }}" | grep -oE "#[0-9]+" | sed 's/#//g')
        echo "issue_numbers=${issue_numbers}" >> $GITHUB_ENV

    - name: Close Issues
      if: env.issue_numbers
      run: |
        for issue in ${{ env.issue_numbers }}; do
          gh issue close "$issue" --repo $GITHUB_REPOSITORY -R $GITHUB_SERVER_URL
          echo "Closed issue #$issue"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

